### ISSUE TITLE
Making a guppy element with an element reference

### ISSUE THREAD

**Issue by saivan** [daniel3735928559/guppy#101]
Sometimes, I don't want to give id's to everything in my page. So that I don't end up with duplicate ids. Also, selecting elements by id is very restrictive; and I'd like to be able to just pass in an element, so I can do:

```js
let elem = document.getElementbyId('someId')
new Guppy(elem)
```

I think this should also work to initialise guppy. What are your thoughts? Happy to make a pr for this one.

**Comment by daniel3735928559** [comment]
Yeah--This seems like strictly more flexibility.  A PR would be welcome!

**Comment by saivan** [comment]
I'm already halfway through this one. But then a few other things struck me while I was working on it. So symbol definitions for example, I noticed you're loading in the symbols inside of guppy. I think letting the user just provide a string as well, that could be a good plan too.

**Comment by daniel3735928559** [comment]
The PR has now been merged and tested.  Everything seems good--thanks!
