### ISSUE TITLE
Incorrect AST for negation

### ISSUE THREAD

**Issue by saivan** [daniel3735928559/guppy#103]
When I input [z, ^, -, 1] it should interpret the negative as a negation for the 1. So I'd expect the following infix representation:

    pow(z, -1)

Instead I'm getting:

    pow(z, sub(1))

Or as an ast:

    ["exponential",[["var",["z"]],["-",[["val",[1]]]]]]

Which is incorrect. The negative is acting as a negation so I'd expect: 

    ["exponential",[["var",["z"]],["val", [-1]]]]

Heres the input on the site:

![image](https://user-images.githubusercontent.com/8543370/47190999-5df6b200-d390-11e8-8613-b208daf6f4bc.png)

**Comment by daniel3735928559** [comment]
I don't know that that's wrong, though it is sort of suboptimal.  It is treating `-` as an operator.  For example, if you did `z ^ - y` you get the same shape of result.  

You could implement a sort of "constant folding" by passing `Doc.evaluate` functions that simplify any subtree that has only "val" children into a single "val" node.  That would also cause e.g. `z ^ 2 + 3` to evaluate to `pow(z,5)`, for instance.

**Comment by saivan** [comment]
Well, I think it would actually lead to an error though wouldn't it? If you take '-' to be a subtraction, then it doesn't have a second argument. Basically when you call sub(1), what should it subtract? You could reimplement sub to behave like `sub(x) = sub(0, x) = -x` and `sub(x, y) = x - y`. But that feels like a bit of a hack.

So if you have a simple input of -3, this should be `sub(3)`, I would expect this to parse as the negated version of the number 3 (which is a different number to 3).

![image](https://user-images.githubusercontent.com/8543370/47255203-e96b6280-d4b8-11e8-93dd-21c0defba5db.png)

I think the only trouble here is the subtraction vs negation issue (that pops up everywhere haha). I think that there has to be some way to distinguish between subtraction and negation. Like if I write 5+-3 (even though that is bad practice); it is a valid mathematical expression; so this is the parse tree we get:

![image](https://user-images.githubusercontent.com/8543370/47255177-94c7e780-d4b8-11e8-807b-bf41639f5c5d.png)

But I think that as a general rule, we should have a function called `neg` which negates a variable or a constant, so long as there isn't a variable or a constant to the left of it. That way, we could do `neg(neg(neg(x)))` and there wouldn't be any issues there.

What are your thoughts?

**Comment by daniel3735928559** [comment]
Adding the line `if(this.value == "-") this.value = "neg";` to Parser.prefix creates the behaviour you describe.  

My original thinking was that `-` is just normally ambiguous and most people will have to check in the implementation whether there are one or two arguments and behave accordingly.  Current examples of this are [here](https://github.com/daniel3735928559/guppy/blob/f74b492209ddbb7c59e248dbd324c62801f7cd6b/src/ast.js#L22), [here](https://github.com/daniel3735928559/guppy/blob/f74b492209ddbb7c59e248dbd324c62801f7cd6b/src/ast.js#L118), and [here](https://github.com/daniel3735928559/guppy/blob/f74b492209ddbb7c59e248dbd324c62801f7cd6b/src/ast.js#L184).  

I agree it's slightly nicer to resolve the ambiguity for the user.  This change will break the code of anyone who handles the current AST.  On the other hand, this is probably a better time than the future to make breaking changes.  I'm unsure; I'll think about it a bit.  If your particular use-case would be made significantly easier as a result, I'd be interesting in hearing the details also.

**Comment by saivan** [comment]
Well, I ended up solving it in the exact same way `-a` just becomes `sub(0, a)`; the trouble is just that it lead to unexpected errors that were very annoying to find haha. For example, if I set up the following sub function:

```js
let sub = (a, b) => a - b
```

Then I used the syntax tree I got from guppy, for this statement (or a more complicated one that contains this), I'd get:

```js
(input) -3
sub(3, undefined)
```

Now the trouble is, silly javascript treats `3-undefined` as `3-0` so when you evaluate it, you'd just get 3. Which would confuse you dearly ❓ haha.

I guess it doesn't lead to any huge issues; so long as we make it clear that this is the way we treat negation, but I think its something we should at least document more clearly in the ast function. 

It just means that the user needs to have a slightly more "sophisticated" subtraction function, that knows the difference between a single negated input and an actual subtraction of two parameters.

**Comment by saivan** [comment]
Yes, thats right. `unary_minus` is effectively just negation, so the discussion here is whether adding negation as a separate command would be useful. So instead of getting `-` in the ast, would it be better to get `neg` where one argument makes sense there? Rather than getting the user to check for it as you're doing here.

I suppose it doesn't matter though, but it does also seem to be good behaviour. I mean the use of the `-` symbol in mathematics really does have two meanings anyway :P so which we decide to support is not really that important. But it should at least be documented.

**Comment by saivan** [comment]
Yep thats right. They are - thats why I think that making this explicit isn't a bad idea. But I'm not so sure.

**Comment by daniel3735928559** [comment]
To possibly make peoples' lives easier, I think it probably makes sense to disambiguate between the two at the moment when the information is available--in the Guppy AST.  I've now made this change in the es6 branch.  The code that consumes ASTs still also understands unary "-", just in case.

**Comment by saivan** [comment]
Awesome!

**Comment by daniel3735928559** [comment]
I've updated the tests now, so I think this is good to close.
