### ISSUE TITLE
Moving Options to the build stage

### ISSUE THREAD

**Issue by saivan** [daniel3735928559/guppy#104]
We already talked about this on gitter, but I thought it would be good to have an issue for it 😄, so basically we want to be able to preload a guppy symbols file from a json file. We can avoid having to then fetch them, which adds an extra http request.

# First Option

So we could do:

```js
import mySymbols from "path/to/my/symbols.json"

Guppy.init({ 
    path: 'some/path', 
    symbols: mySymbols 
})
```

# Second Option

Alternatively, we could refactor the code so that we no longer need guppy-init at all. So that all of the code is synchronous.  We could just do:

```js
new Guppy({ symbols })
```

If none are provided, it will just use the default symbols defined in the library. To achieve this, we need to remove guppys ability to make XHR requests, which is good because things would be much more explicit that way.

**Comment by daniel3735928559** [comment]
I've started something in this direction on the es6 branch.  The goal is to remove both all deeply nested `config` dictionaries as well as all XHR from Guppy.  An example of using the new interface (as it currently stands, anyways) can be found at https://github.com/daniel3735928559/guppy/blob/es6/site/examples/calc/calc.html

**Comment by daniel3735928559** [comment]
This is now live, more or less following the second option.  However for now I've left the initialisation options to runtime, as my preference is very much that people using the library generally don't have to build it, (so leaving the `configure` and `event` functions for configuring it at runtime).

Did you have in mind some way to also package, say, new defaults at build time?

**Comment by saivan** [comment]
I mean, you can just import the json and it would work out of the box right?

**Comment by daniel3735928559** [comment]
This specific item appears solved. There is a little bit of related but different work to do on the setup API, and I'll make specific issues for those items as they come up.

**Comment by saivan** [comment]
The `DEFAULT_SYMBOLS` are currently hardcoded into guppy. I have no way to override the default symbols with my own ones. I know I can define new symbols, but I'd like to supply a whole new file based off of your one with my own symbols instead.
