### ISSUE TITLE
Offering support to add examples into jsfiddle

### ISSUE THREAD

**Issue by mmuekk** [daniel3735928559/guppy#111]
Hello Daniel,
first of all. Great work and thanks for making Guppy available for us.

Would you like for me to update your examples page, https://guppy.js.org/site/examples, to be live editable using https://jsfiddle.net ?

**Comment by daniel3735928559** [comment]
I'd be interested in seeing one example converted first, to better get a sense for what this would look like.  It would probably be a big improvement on the kludgey iframe thing currently in use, but I'd like to preserve the simplicity of presentation for someone looking for a quick, self-contained code example.  (So, for example, the examples as much as possible are not broken up into separate js/css/html files so that everything the user needs to see is in one place.  Maybe with this multi-panel view that wouldn't be necessary though.)

**Comment by saivan** [comment]
Whilst you can include guppy into codepen. I think it would be clearer for a user if you included it as a script tag in the html section :P that way a user could literally copy and paste the example.

Although I do like being able to develop directly on the demo page.

**Comment by mmuekk** [comment]
Script included added to HTML section, so copy & paste is now possible.

Since Demo page is very strait, what do you think about, replacing
 **https://guppy.js.org/site/examples/basic** link
with **https://codepen.io/mmuekk/pen/zMYgpO**?

PS - you can create your own and removing my name from Url

**Comment by daniel3735928559** [comment]
That seems a really clean way to present the examples.  I'm happy moving over to this.  It probably would be better to have the examples under my account control, so I'll get a move on that.

One last concern: Having the examples reference the build at guppy.js.org may encourage people to effectively use github pages as a CDN.  Some initial experiments suggest that this might actually not be terrible: The MIME type is correct, there are reasonable expiry times, the server seems to apparently be backed by cloudflare anyways.  I'll do further research to ensure this isn't considered impolite to github, say.

**Comment by daniel3735928559** [comment]
Seems like after more investigation as though is fine.  I've started moving some examples over--first three done so far.  I think it is an improvement, but am interested in any other opinions: https://guppy.js.org/site/examples/

**Comment by saivan** [comment]
I would use an embed and just have them directly in that site (just a suggestion)

**Comment by mmuekk** [comment]
My opinion is that looks great and make easier for looking and testing your framework
