### ISSUE TITLE
Question: Wordwrap or similar

### ISSUE THREAD

**Issue by mmuekk** [daniel3735928559/guppy#113]
Hi Daniel,

in my project I have a large formula that dont fit in the Editor area, even with max. width.
Does GuppyJs as 'wordwrap' functionality or similar function for these cases?

Thanks

**Comment by saivan** [comment]
It is possible to put guppy inside a div with overflow set to scroll. Not sure if you want to actually see the whole equation at once.

**Comment by daniel3735928559** [comment]
It appears that KaTeX supports word wrapping in "inline" mode (the default) as per Khan/KaTeX#1287.  This might therefore just work after #92 is solved.

**Comment by daniel3735928559** [comment]
This seems to work now.  If I go to guppy.js.org and enter something like 1-1-1-1-1-1-1-1-1-1... I now get reasonable wrapping behaviour.  Feel free to reopen if your use-case is not met by the new changes.
