### ISSUE TITLE
Keymap for f-nodes

### ISSUE THREAD

**Issue by daniel3735928559** [daniel3735928559/guppy#12]
Would like to be able to control programatically what all keys do within an f-node.  For example, would like to make it so that the keystrokes `sin^2` result in something that looks like `sin^2()` rather than `sin(()^2)`.

**Comment by ylemkimon** [comment]
In insert_symbol,
```
if (sym_name == "exp" && this.caret == 0 && this.current.parentNode.parentNode.nodeName == 'f' && this.current.parentNode.firstChild == this.current.parentNode.lastChild)
		this.current = this.current.parentNode.parentNode.nextSibling;
```

Moving out when ^ is entered inside blank f node like above would accomplish (sin())^2.

**Comment by daniel3735928559** [comment]
Yeah--that works.  I am hesitant about introducing symbol-specific behaviour into the code itself, rather than somehow into the definitions of the symbols, however I am not sure this is something that can be declaratively expressed.  

Also, one of the complaints I've got has been that you can't get the editor to display how LaTeX would render `\sin^2(x)`, which is what many students are used to seeing.  It would of course be possible to create a special behaviour for just exponentiation and certain function symbols, but that doesn't sit well with me.  Having said that, there doesn't seem to be a nice generalisable way to do it either, so if that is what is asked for.

**Comment by daniel3735928559** [comment]
I am unconvinced there is a use-case for this.  Closing until some application actually needs it.
