### ISSUE TITLE
Is there a way to insert xml into a guppy editor?

### ISSUE THREAD

**Issue by ibreaker14** [daniel3735928559/guppy#129]
I'm trying to insert the contents of one guppy object into another without replacement. 
I've been successful at this by extracting the doc object `g1.engine.insert_doc(g2.doc());` (Basically, I want to save the contents of the editor somewhere for later use). However, I do not believe this is the best way to do this because the doc object takes up a lot of space in memory. Are there any other approaches to this?

**Comment by ibreaker14** [comment]
Oops, I found the solution right after posting this. I was able to achieve my goal with `g2.engine.import_text(g1.engine.get_content("text"));`

**Comment by daniel3735928559** [comment]
It isn't the most efficient, but that's the method supported in the public API. There is also the undocumented internal interface `g1.engine.insert_nodes(xml_document.childNodes)`which will be faster if you're finding a need for the extra speed.
