### ISSUE TITLE
Retrieve arguments from function

### ISSUE THREAD

**Issue by ibreaker14** [daniel3735928559/guppy#142]
Is there a way to retrieve the arguments from a function? For instance, if I typed in `sin(3+x)+cos(x)` into a guppy field, I'd like to get the `3+x` part back by selectively passing in `sin` into some function.

**Comment by saivan** [comment]
Yes there is. Get the ast (the abstract syntax tree) and parse it to get the part that you want.

**Comment by ibreaker14** [comment]
@saivan that's exactly what I've been doing. I was wondering if there was something more straight-forward built into the library.

**Comment by daniel3735928559** [comment]
I guess I'd like to know more about:

* How would this library function's behaviour actually be defined? For example, what is the result of this function when faced with `sin(sin(x)+sin(2))`?

* How broadly useful is this? I am not aware of a common use-case that needs this, but if you can provide some context behind what you're doing with it, I might just be insufficiently aware/imaginative.
