### ISSUE TITLE
Make backslash provide textbox so that shortcuts don't have to be prefix-free

### ISSUE THREAD

**Issue by daniel3735928559** [daniel3735928559/guppy#15]
It would be nice to be able to use "logp" as the shortcut for p-adic logarithm and not have this conflict with "log" for natural logarithm.  One possible interface for this would be to have backslash open a box where you could type the name of an element (without auto-replacement) and then "enter" or "space" would insert the element in place of the box.  

An alternative interface would be for there to be no autoreplacement, but space would trigger the replacement code that currently runs after every character insertion.

**Comment by kalbhairab** [comment]
please make the code tab completion for root, integrate, diff, etc

**Comment by daniel3735928559** [comment]
Good idea; noted.

**Comment by daniel3735928559** [comment]
As of 5cab2af84ab67b98302f20e3565294dab33b869d some version of this should now work.
