### ISSUE TITLE
Pressing keys on the numeric keypad (on the right of some qwerty keyboard) doesn't work.

### ISSUE THREAD

**Issue by seanlip** [daniel3735928559/guppy#16]
Typing '9' in a guppy textarea works if the 9 key is the one above and between the 'I' and the 'O' of a standard qwerty keyboard.

However, typing '9' (or anything) on the numeric keypad doesn't register anything, even though a keystroke is recorded in the console logs.

**Comment by daniel3735928559** [comment]
There is a more general issue #24 whose resolution should address this also, so I'm closing this.
