### ISSUE TITLE
The ready_callback() mentioned in the README never seems to fire.

### ISSUE THREAD

**Issue by seanlip** [daniel3735928559/guppy#18]
I assigned my instance a ready_callback as follows:

          guppyInstance.ready_callback = function() {
            console.log('ready');
          };

However, 'ready' is never printed to the terminal. It is possible to type into the instance and focus it, though.

**Comment by daniel3735928559** [comment]
Hmm.  I believe it should run if you set this on an instance before running Guppy.guppy_init,  but it may not run if you put that line after the guppy_init one, depending on how quickly the init runs.  You can try that on the version you have now, or commit 607fc5a301ea8adfa1a7e7adb051a1be780d0e81 should make it work properly in either case.

**Comment by seanlip** [comment]
Hm, we always run Guppy.guppy_init before doing anything with individual guppy instances.

Unfortunately, guppy master is now causing an error regardless of whether or not I assign the above. When I create a new Guppy instance, it tells me:

     TypeError: this.ready_callback is not a function at new Guppy (guppy.js:56)

**Comment by daniel3735928559** [comment]
I think this is fixed now.  Reopen if you can reproduce on your end though.
