### ISSUE TITLE
Guppy doesn't seem to register the state of the Ctrl key.

### ISSUE THREAD

**Issue by seanlip** [daniel3735928559/guppy#19]
I have a use case where I type into an instance of Guppy, hit Ctrl+Enter, and then that instance of Guppy disappears and a new instance of Guppy appears. Typing into the second instance of Guppy produces a string of errors along the following lines:

```
Uncaught TypeError: Cannot read property 'length' of undefinedGuppy.sel_cut @ guppy.js:709
Guppy.key_down @ guppy.js:1159
guppy.js:1155 88
guppy.js:709 Uncaught TypeError: Cannot read property 'length' of undefined
```

I believe guppy still thinks I'm holding down the Ctrl key, when I'm no longer doing so.

**Comment by daniel3735928559** [comment]
I have pushed a commit that I think fixes this; let me know if it actually does.

**Comment by seanlip** [comment]
Yes, the issue is now fixed, thanks! (Though I had to get around the error mentioned in #18 first.)
