### ISSUE TITLE
Normal text typing

### ISSUE THREAD

**Issue by PeterBocan** [daniel3735928559/guppy#21]
Is there any way I could type normal text into editor?

**Comment by daniel3735928559** [comment]
Would it be enough to have an element that behaves like LaTeX's `\text`?  

You can kind of get this by adding an entry like

```
    "text":
    {"output":{
        "latex":["\\text{",1,"}"],
        "calc":["text(",1,")"]},
     "current":0,
     "type":"text"},
```

to the dictionary in guppy/symbols.json, except there's a rendering error when the cursor is in the text element.  I shall work on fixing this, as there are many other use-cases for a text mode.  If this worked as advertised, would it do what you need?

**Comment by daniel3735928559** [comment]
On further investigation, it looks like https://github.com/Khan/KaTeX/issues/5 makes this relatively difficult.

**Comment by daniel3735928559** [comment]
OK--I've bodged something until the aforementioned issue can be fixed.  The cursor will look different for normal text editing, but it seems to work as intended.  Feel free to reopen if this isn't adequate.
