### ISSUE TITLE
"insert_string" method call issues

### ISSUE THREAD

**Issue by stanciupaul** [daniel3735928559/guppy#30]
I tried to call `insert_string()` and it doesn't work properly. My call looks like this: `Guppy.instances.my_instance.insert_string('x');`.

There are 2 scenarios:
- when editor is focused and method is called, inserted string is displayed only after mouse is moved inside workspace.
- when editor is not focused and method is called, the following error occurs and inserted string is displayed only after Guppy container is clicked.

```
guppy.js:1477 Uncaught TypeError: Cannot read property 'current' of null(…)

	Guppy.check_for_symbol @ guppy.js:1477

	Guppy.insert_string @ guppy.js:1018

	(anonymous function) @ VM9271:1
```

There are also a lot of 'ASD' logs in console.

**Comment by daniel3735928559** [comment]
Yeah--this was very broken.  Thanks for the clean and clear report!  It should be fixed now.  Try it out and let me know.

**Comment by stanciupaul** [comment]
It works perfect now. Thank you for fast fix.
