### ISSUE TITLE
Publish a module on npm

### ISSUE THREAD

**Issue by chmln** [daniel3735928559/guppy#32]
Hello,

First of all, thank you for the library.
Using MathQuill has been a nightmare.

It'd be great to have `guppy` on npm, so its easier to install and update as opposed to just downloading.
Its very easy to [create](https://docs.npmjs.com/cli/init) and [publish](https://docs.npmjs.com/cli/publish) a package.

**Comment by daniel3735928559** [comment]
This looks like a good idea.  I shall package the editor roughly as it is now into a tested release and then create an npm package out of that.  Could be a few days yet, but I have added it to the to-do list.

**Comment by daniel3735928559** [comment]
There is now a module--`guppymath` on npm that you should be able to install.  I'm not entirely sure I followed all best practices in doing so, but hopefully this should be a good first step and will be helpful.
