### ISSUE TITLE
index.html of release 1.0 doesn't work.

### ISSUE THREAD

**Issue by kalbhairab** [daniel3735928559/guppy#34]
My screen looks like this and doesn't work offline. Do i need to install some other library.

![image](https://cloud.githubusercontent.com/assets/12480299/20557255/e23095da-b192-11e6-9b89-7d68eb89262a.png)

**Comment by daniel3735928559** [comment]
The 1.0.0 index.html should in theory be able to work offline.  

UC browser doesn't seem to have a Linux version, and it will be a few days before I have easy access to a Windows VM.  I will try it out then, but meanwhile, is there any javascript console output that might indicate what errors it is seeing?

**Comment by ylemkimon** [comment]
I had same problem, and it was due to cross origin security policy.

Refer to [how to run things locally](https://threejs.org/docs/#Manual/Getting_Started/How_to_run_things_locally).

**Comment by daniel3735928559** [comment]
Just tried it on UC browser--this appears to indeed be the issue.  Unsure whether UC browser has a way around this, but generally speaking, when I test locally, I use a simple HTTP server from the Guppy root dir: 

```python -m http.server --bind 127.0.0.1 8000```

(replace http.server with SimpleHTTPServer if using Python 2) and then can test by visiting the page at localhost:8000.
