### ISSUE TITLE
Expose an API for setting focus on Guppy, instead of autofocusing on it immediately after it's initialized.

### ISSUE THREAD

**Issue by seanlip** [daniel3735928559/guppy#4]
If a guppy textarea is added dynamically to a page, it steals the focus. This probably shouldn't happen.

**Comment by daniel3735928559** [comment]
I've added `activate()` and `deactivate()` as described in the docs, and changed the key events to be div-specific.  Hopefully this will fix the use-case in question.

**Comment by daniel3735928559** [comment]
Looks like this one is fixed; thanks!
