### ISSUE TITLE
Create an optional button-based GUI

### ISSUE THREAD

**Issue by daniel3735928559** [daniel3735928559/guppy#43]
We want to include the option for the editor to come with buttons that users can click to insert any of the available symbols.  These buttons should be generated from the loaded symbols.  The symbols should have some metadata that allows the corresponding buttons to be sensibly grouped.

**Comment by uperetz** [comment]
I've done the first go for this on my branch - it's moduled out so you can use it alone. Added to the example. Currently the only style is "expanded", as in button per symbol. I may go to menu based groupings later on.

**Comment by daniel3735928559** [comment]
First attempt at integrating this is done as of 6b43f00f978e1c5ebfb3fd93670414f7d50e9663

**Comment by uperetz** [comment]
I'm having trouble using the GUI, can you add it to the index?

**Comment by daniel3735928559** [comment]
A full example of using the GUI in action is here: 

https://daniel3735928559.github.io/guppy/examples/osk.html

I'll try adding it to the demo page proper, but I think that will require reworking it a little (in a way that needs to happen anyways, to be fair).

**Comment by abhinov2** [comment]
While typing text how to give an space .

**Comment by daniel3735928559** [comment]
Ah--that is not currently supported, but it should be.  I shall fix it, but unfortunately will quite possibly not have the time this week.
