### ISSUE TITLE
Clearing guppy

### ISSUE THREAD

**Issue by jiggzson** [daniel3735928559/guppy#48]
I'm planning to use guppy as an input for entering expressions and equations. However after reading the documentation I wasn't able to find a way to clear the editor. I implemented this utility function hoping that would work
```javascript
function clear() {
    guppy.end();
    var n = getText().length;
    while(n--)
        guppy.backspace();
    guppy.home();
}
```
where guppy is the editor instance. This unfortunately causes the editor to become unselectable and the following error to be thrown.
```bash
    Uncaught TypeError: Cannot read property 'setAttribute' of null
    at Guppy.render_node (guppy.min.js:1709)
    at Guppy.render (guppy.min.js:2161)
    at Guppy.mouse_move (guppy.min.js:1554)
```
Is there an existing way to clear the editor? If not a better way?
One more thing, when initially selecting the editor this error gets thrown
```bash
    Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.Guppy.get_loc (guppy.min.js:1418)
    at Guppy.select_to (guppy.min.js:1481)
    at Guppy.mouse_move (guppy.min.js:1557)
```

Thanks in advance.

**Comment by daniel3735928559** [comment]
This is slightly obscure, but you can clear the editor (assuming the instance is called `guppy`) with: 

```
guppy.set_content('<m><e/></m>');
guppy.render();
```

I've tested this and it appears to work (it clears the editor, and the editor seems to work as intended after that, and the undo history is cleared also).

Nevertheless the errors you got--both with your `clear` method and on initially selecting the editor seem like they shouldn't happen, so I shall investigate further.  

If you run into any other guppy issues blocking your project, I'll be happy to try to troubleshoot further!

**Comment by jiggzson** [comment]
Thank you for the quick response. This clears up the issue in one or two cases but mainly still persist if the input is entered incorrectly for instance if the user inputs **diff(x, cos(x))** instead of the other way around **diff(cos(x), x)** the input seems to break after calling clear. Hopefully this can be addressed in the future. Thanks for all your hard work. I'll make sure to credit your project.

**Comment by daniel3735928559** [comment]
Ah--I see.  It's an issue with when the editor is inactive when it is cleared in this way (I was testing without removing focus from the editor).  I've played around with it and I believe I found the bug and fixed it.  The clear function should now be: 

```
guppy.set_content('<m><e/></m>');
guppy.render(true);
```

Let me know how that works.

**Comment by jiggzson** [comment]
Unfortunately the issue persists for the **diff(x, cos(x))** example. I did notice something interesting. If you go to symbols.json and change the code for diff from
```json
"diff":
    {"output":{
        "latex":"\\frac{d}{d{$1}}{$2}",
	"text":"diff({$2},{$1})"},
     "current":0,
     "type":"derivative",
     "attrs":{
	 "up":[2,2],
	 "down":[1,1],
	 "bracket":["yes","yes"],
	 "name":["function","variable"]}
    },
``` 
to
```json
"diff":
    {"output":{
        "latex":"\\frac{d}{d{$1}}{$2}",
	"text":"diff({$2},{$1})"},
     "current":0,
     "type":"derivative",
     "attrs":{
	 "up":[2,2],
	 "down":[1,1],
	 "bracket":["yes","yes"],
	 "name":["function","function"]}
    },
```
The issue goes away. Can it be related to the checking of the second parameter?

**Comment by daniel3735928559** [comment]
OK--I believe I have finally tracked down the issue.  I've pushed the changes--try now and let me know.

**Comment by jiggzson** [comment]
Interestingly it now breaks in all cases not just erroneous input. I really appreciate your effort but as I stated before changing the settings in symbols.json provides me with a working solution. I'm always curious to see where my projects are being used so here's the link in case you're interested.
http://nerdamer.com/demo.html
Currently I use a text input as my primary input and the user has to opt for a visual editor. I'd like to someday use guppy as my primary input since it handling of text and LaTeX is the best IMHO but unfortunately it doesn't trigger the mobile keyboard as I stated in issue #49.

**Comment by daniel3735928559** [comment]
OK.  If you're fine with the workaround, then I'm happy.  However, in debugging this, I've found further issues with the activate/deactivate code that I've gone ahead and resolved.  This may also fix your issue (properly this time), although the fact that changing the symbols.json fixed your issue kind of suggests there might be more going on also.

**Comment by daniel3735928559** [comment]
Also, the calculator project is neat!  I'll let you know if I ever find something for the mobile keyboard issue--others have asked for this as well but nothing I've tried has worked yet.

**Comment by daniel3735928559** [comment]
I am still not sure what was causing this issue, but have made some changes to fix timing issues and AFAICT it is no longer present in the latest version.  Feel free to reopen if it resurfaces.
