### ISSUE TITLE
Make Guppy look more 'editable'

### ISSUE THREAD

**Issue by seanlip** [daniel3735928559/guppy#5]
Textareas and input fields in HTML have visual affordances that make them look editable. It would be nice to add these (borders, shading, etc.) to Guppy, so that it's visually clear that it's something the user should type into.

**Comment by daniel3735928559** [comment]
I've added what I think might be similar borders/shading to other text editors.  Feel free to close the issue if you find the change sufficient, or let me know if you have an idea for a look that might be more indicative!
