### ISSUE TITLE
guppy will only load if called before get_symbols finishes

### ISSUE THREAD

**Issue by TMeerhof** [daniel3735928559/guppy#50]
If you initiate the editor before the get_symbols is done it works fine, but if you wait for the get_symbols call to finish i get errors (tested in chrome and firefox)
See this fiddle:
https://jsfiddle.net/Timlessonup/9mngc9gs/

BTW, the get_symbols callback is never called.

Thank you.

**Comment by daniel3735928559** [comment]
Good catch.  This turns out to be a slightly subtle one.  I think I have fixed the main issue wherein initialisation fails if get_symbols has completed, but the callback issue may still be present.  This definitely also merits inclusion into the test files.

**Comment by TMeerhof** [comment]
Thank you for the quick response and fix, it works. The callback is not essential for us, so don't feel rushed, it was just something i notices while reproducing the bug. 
We will try to integrate guppy in our product, if all goes well we would like to donate, could you send you're contact details to tim@lessonup.nl so we can get in touch.

**Comment by daniel3735928559** [comment]
So it turns out that the get_symbols callback was simply never called.  Now it should be.
