### ISSUE TITLE
Can't type "<" or ">"

### ISSUE THREAD

**Issue by Oishikatta** [daniel3735928559/guppy#51]
On the page at https://daniel3735928559.github.io/guppy/

When trying to type an expression such as "a < b", the "<" will not be shown and an error is produced in console:

    Uncaught TypeError: Cannot read property 'type' of undefined
    at Guppy.insert_symbol (guppy.js:958)

It seems like there is an "angle" defined here: https://github.com/daniel3735928559/guppy/blob/master/src/guppy.js#L1756

But no corresponding entry in symbols.json?

**Comment by daniel3735928559** [comment]
Yeah, that seems to have been a forgotten loose end.  It should now be fixed!

**Comment by Oishikatta** [comment]
Awesome, thank you!
