### ISSUE TITLE
can't type a x times integral

### ISSUE THREAD

**Issue by ailisp** [daniel3735928559/guppy#52]
If I type xint, I want it to be x times integral, but it appear as greek letter xi and nt.

**Comment by daniel3735928559** [comment]
Yeah--this is kind of a tough one.  The auto-replacement of strings with symbols is pretty fluid when it works, but it makes it hard to type certain things.  An even worse example is "theta", which will always come out as `th\eta`.  

In your particular example, the current solution intended is that you type `xi`, which gets replaced with `\xi`, and then you type Ctrl+z to undo the replacement, bringing it back to `xi` so you continue typing `xint` which becomes `x\int`.  Another possibility is typing `int` and then going back and adding the `x` after.  

I would agree that that's not terribly intuitive, and I've gone back and forth on different interfaces.  On balance, however, I think I like the auto-replacement as being the most fluid behaviour most of the time, and that using Ctrl+z to undo any auto-replacements you didn't intend is pretty quick.  And even if Ctrl+z doesn't happen to cross a user's mind, there are other (albeit slower) workarounds that probably will.  

The solution to the "`\theta` vs `th\eta`" problem, on the other hand, will in future be #15.  

I am open to suggestions or thoughts; my current preference is to preserve the speed with which a majority of things can be entered, even if it means to allow some less intuitive behaviour in some cases.

**Comment by ailisp** [comment]
I agree, speed is more important than these corner cases. Guppy is much
faster than any other equation input I have ever seen. But I do have a
suggestion, maybe not work. Can we make use of spacebar, it did not produce
space, bur work as invisible separater so when type "x spacebar int" the
auto completion start at previous spacebar mark? And after autocompletion
finished the mark is cleared.
Sincerely,
Bo

2017年2月17日 上午8:23，"D" <notifications@github.com>写道：

**Comment by daniel3735928559** [comment]
Hmm.  That seems pretty natural.  I'd have to think about how that would work, since later as you're editing the equation, if you want to change x to xi, you would want the space to no longer be there, or something.  

Actually, I have a thought for how to implement your idea--let me play around with it for a day or two.

**Comment by daniel3735928559** [comment]
I've gone ahead and made a first attempt.   Pressing space puts a temporary invisible separator that will remain as you continue to type more characters, but will be removed the moment anything any navigation (mouse clicks, right/left/etc.) happens.  It seems to feel pretty natural and doesn't interfere with any other behaviour, so I think I'll make it the default, assuming no issues come up with it.  Thanks for the suggestion!  Let me know how you find it (and especially if it doesn't work for you).

**Comment by ailisp** [comment]
Great, I have tried, it now works perfectly! Thank you.
