### ISSUE TITLE
Can't type some symbols on non-US keyboards.

### ISSUE THREAD

**Issue by Oishikatta** [daniel3735928559/guppy#53]
The Mousetrap bindings for these symbols:

`    "shift+6":"exp",
    "shift+8":"*",
    "shift+9":"paren",
    "shift+,":"less",
    "shift+.":"greater",
`

Only make sense for US (or similar) keyboard layouts.

Mousetrap seems supports binding the desired character directly, i.e. "^" instead of "shift+6" and so on, which would allow compatibility with non-US keyboards.

Example: https://github.com/daniel3735928559/guppy/compare/master...Oishikatta:gh-pages

However, I'm unsure if the bindings were written the way they are for a particular purpose.

**Comment by daniel3735928559** [comment]
I didn't know mousetrap could handle the symbols directly (which is the only reason I did it the way I did).  I've changed it now and it still works fine on my keyboard.  Thanks for the suggestion!
