### ISSUE TITLE
Suggestion: use \frac \int .. etc instead of frac int

### ISSUE THREAD

**Issue by cwhy** [daniel3735928559/guppy#54]
I personally feel that the effort to add a \ before commands for users is minimal, but it may cause increasing unwanted commands appear as guppy adds more functionality.

**Comment by daniel3735928559** [comment]
I've been back and forth on this, and it kind of depends on use-case.  From the perspective of education software, the more the editor just works the way a non-LaTeX-savvy student expects, the better.  And being able to just start typing "fraction" and having the symbol show up at "frac" I think does that.  (So does being able to click on a fraction button, which is a thing I still need to do.)

For the use in, say, writing mathematics (where there might be tons of symbols defined) the backslash interface might be better suited.  Right now (as of a few days ago), you can use \ to enter commands, and even tab-complete them, but you don't have to if you'd rather not.  If the auto-replacement of commands starts to get in the way, it might be useful to have a configuration option to turn that off.  That I can easily and probably will add.  

Thoughts?  Is the current support for backslash-prefixed commands not easy to use?  Or is it just that you'd rather that were the only interface, say?

**Comment by jiggzson** [comment]
It would be nice if this can be a configurable option. I ran into this issue with my project. Not for \frac but for \exp. I have a function named expand which couldn't be typed because it would be triggered by exp. In that case turning off the backslash-prefixed command for a particular command would be useful.

**Comment by daniel3735928559** [comment]
Sounds good.  Added in 6feb2bada338cd4012c17187050633a4cccf1ae3.  Documentation in [doc/api.md](https://github.com/daniel3735928559/guppy/blob/master/doc/api.md).  Basically, in the constructor, `config.options.autoreplace` is a boolean (defaulting to true) that toggles the autoreplace behaviour.  

OP, let me know if this fills your need as well.  I've left the autoreplace on in the demo page, but if you want to test what it's like without it, go to the [demo page](https://daniel3735928559.github.io/guppy/), refresh with Ctrl+shift+r (or avoid cache hits by other means), open up a Javascript console, and put in:

```
Guppy.instances.guppy1.autoreplace = false
```

Then the editor should have the autoreplacement behaviour disabled.
