### ISSUE TITLE
Guppy div with math mixed with text

### ISSUE THREAD

**Issue by uperetz** [daniel3735928559/guppy#56]
Hi Daniel,

I've been working on implementing this for a couple of weeks, and it's ready. Plus I did some major refactor on the code - essentially splitting the file to many according to methods. I would like to contribute this plus a few trivial bug fixes if this is something you might be interested in - note I still have to implement Guppy being toggle-able between pure math, and text mix, so it's not production ready yet.

If you think this is cool I'd like to fork a branch and show you what I've done.
Uria

**Comment by daniel3735928559** [comment]
That sounds cool--I'd definitely be interested to see!  

Also, refactoring is good.  The particular way in which the code is factored depends on what sorts of future uses need to be supported, so because I have certain uses in mind, I have a corresponding specific factorisation in mind.  Even so, I'll be happy to take a look at whatever you've come up with.

**Comment by uperetz** [comment]
Great, I'll submit the request.

**Comment by daniel3735928559** [comment]
Closing.  Interested parties refer to #57 for the discussion.

**Comment by uperetz** [comment]
Sorry it's taking me a while to replay, this is a side project of my side
project, so I can only work in bursts. Looks much better, and I'll try
integrating this to my other project later so I can better code review.
Specifically checkout the "osk".

On a side note your main Guppy file is still giant, and I don't see how it
fits with your conceptualization you described before. In any case, if you
feel everything in there should be together you can create a 'main'
directory, and in there break everything up (though some of the code there
feels like it should be in files you created, like 'render' and
`render_node`. All the definitions seem like an after though as well, I
would separate them as well.

In any case, looking forward what do you feel would be the next thing to
work on?

1. If you started on text editor integration that could be a possibility (I
already confessed this would be awesome).

2. I can also migrate in some of the code I have working with Guppy, as an
example or core - mainly a form with a "question" and possible solutions.
Additional Guppy divs a part of the same equation are added by pressing
"enter", and a "+" button adds a new equation. Submission collects all
these for posting or whatever. Tabs are caught in the entire document and
circulate the different Guppies. Perhaps a module for easy document
creation? The functions are already set up, including a side menu with the
GUI, with a drop-down menu (that you integrated already).

3. If you need help I want to be end-goal driven - less work on fluff for
now, and more on core capabilities. Since this is yours I'll take your cue
here.

If you want to make things easier, add me as a dev with permissions on a
separate branch (as in not on master or gh-pages).

**Comment by daniel3735928559** [comment]
All the v2.0 goals are now done, so what's now primary is more testing to get out of alpha.  This involves moving from developing the editor towards trying to use the editor to accomplish its two original primary goals, and preferably creating examples (in the new examples directory) of it doing so: 

* Support various online learning scenarios, including both teachers creating content and students interacting with it.  To that end, a few things come to mind in no particular order:

  * Integration into a general-purpose editor.  I've already done some with CodeMirror in kit (though that'll need a little revamping), but QuillJS looks like a great one to do also, and better suited to a teacher's use-case.  I don't really have the bandwidth to spin up on that myself anytime soon, however.

  * Create examples of online problem sets.  Something like a page that is mobile friendly (so somehow integrates the OSK or similar interface) with questions and guppy answer-boxes.  The example you discuss sounds like it would be very useful.

  * Integrate with an automatic solution checker such as the math-expressions library.  

  * A tool that combines all of those, maybe by adding a complete package to an existing LMS seems like a reasonable end-state to shoot for.  

* Support the easy creation of documents with semantically meaningful storage of mathematics expressions.  For example, just like some IDEs have for computer code, I'd like to be able to read a mathematical document and click on an equation and be given the option to jump to where a symbol in the equation was defined, or to see all the propositions it is used in, say.  This is mostly where development of kit is aiming.

Hopefully working on those will reveal flaws in the code or choices of abstraction.  After are few iterations like that, I'll start have a little more confidence that it is handling these use-cases smoothly and I'll bring version 2 out of alpha.

I very much get the business of working in bursts.  For that reason it would be extremely convenient to be able to simply add you as a contributor on a "dev" branch or similar, but github doesn't seem to support such branch-specific permissioning for contributors, from what I could find.  I can promise that even if I'm not on one of my bursts I should be able to at least try to review new examples (as opposed to core code changes) with alacrity.

(Also, to the side point: The refactoring was done mostly with an eye towards reusability: The frontend, backend, and standalone document management are all now separate, so e.g. the backend functions can be used for writing tests and document code can be used for a standalone renderer.  Breaking up those files further may indeed be good hygiene on top of that, and the structure is still a little ad hoc, but it is a lower priority now that it at least does the job.)
