### ISSUE TITLE
Loading symbols dynamically

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#59]
Dear Daniel,

lovely little plugin, really beautiful. 

I have a question, the documentation clearly says that symbols have to be loaded once per page and before any instantiation of a guppy editor, however is there anyway one could dynamically add symbols JSON object after a guppy editor is created?

**Comment by aurovrata** [comment]
Calling the function,

`GuppySymbols.symb_raw(symb_name,latex_symb,text_symb)`

after the GuppyEditor has been initialised seems to be working, for example,

`GuppySymbols.symb_raw("lcc" ,"L_{cc}","Lcc");`

**Comment by daniel3735928559** [comment]
Hello!

Right now the interface is slightly in flux since it's in the middle of a refactoring.  So, for the moment, what should work is (say `guppy1` is your instance of a `GuppyEditor`): 

```
guppy1.backend.get_symbols("url_of_new_symbols.json")
```

Optionally, you can pass a function as the second parameter that will be called when the symbols are done loading.

Alternatively, 

```
GuppySymbols.get_symbols("url_of_new_symbols.json")
```

should do the same thing.  

I don't know that this will still be true after the refactoring is done, but I'll update this issue if something changes.

**Comment by aurovrata** [comment]
thanks for the heads-up.  Good luck with the refactoring.

**Comment by aurovrata** [comment]
`guppy1.backend.get_symbols("url_of_new_symbols.json")`

this is a neat because it allow me to associate custom symbols for a specific function/editor.  However, it still requires me to build a json file and load it into the plugin.  

It would be much easier if I could load individual  symbols into the editor with something like,

`guppy1.backend.symb_raw(value , laTex, value);`

but it throws an error, `TypeError:guppy1.backend.symb_raw is not a function`

anyway way I can expose symb_raw in the front end?

**Comment by aurovrata** [comment]
> anyway way I can expose symb_raw in the front end?

I tried inserting the following in guppy_editor.js and rebuilding...

`Guppy.symb_raw = function(symb_name,latex_symb,text_symb){
  GuppySymbols.symb_raw(symb_name,latex_symb,text_symb);
}`

 but no luck, still unable to expose symb_raw function, any tips?

I have a front-end form where users can create multiple functions and select/create constants to use within each function, however I want to restrict the constants used/created for each function editor, so that constants created in a previous guppy editor cannot be used in a subsequent one.

**Comment by aurovrata** [comment]
PS: I just realised that 

> `guppy1.backend.get_symbols("url_of_new_symbols.json")`

doesn't work either, get_symbols doesn't seem to be exposed to the instance of Guppy() (tested with the latest release.

**Comment by daniel3735928559** [comment]
Exposing symb_raw (and in general more of the symbol functions) sounds like a good idea.  Let me think a little about this and get back to you.  Certainly there should be a way of modifying symbols (especially simple ones) that's easier than writing a whole JSON file (which is rather onerous).  

Also, the latest release is pretty out of date.  If the above doesn't work with the version at HEAD, then I'm a little surprised and I'll look into it.  At any rate, my hope is to carve out a new release around the end of this week (hence all the new tests, etc.) so the interface should be settled soon.  Sorry for everything being in kind of in flux all at once.

**Comment by aurovrata** [comment]
HI Daniel,

this sunday I have a little extra time and dived into your code to see if I could get the functionality I seek and yet change as little of the original design.  I came up with the idea of introducing a symbol repository (object key/value collection) within the backend object,

```
var GuppyBackend = function(config){
  ...
  this.symbols = {};
  ...
}
```

Next, I extended the backend object with a few more methods to manage this editor-specific symbol collection, namely an add, remove and check method, 

```
GuppyBackend.prototype.add_symb = function(symb_obj){...}
GuppyBackend.prototype.remove_symb = function(symbol){...}
GuppyBackend.prototype.has_symb = function(symbol){...}
```

In order for these symbols to be recognised, I also had to modify the way the plugin interacts with the `GuppySymbols.symbols` collection, by giving precedence to the editor-instance symbols, here is an example,
```
GuppyBackend.prototype.check_for_symbol = function(){
    var instance = this;
    if(GuppyUtils.is_text(this.current)) return;
    var all_symbols = this.symbols;
    for(var s in GuppySymbols.symbols){
      if(s in all_symbols) continue;
      all_symbols[s] = GuppySymbols.symbols[s];
    }
    for(s in all_symbols){...
```

I changed only the [guppy_backend.js file, which I forked](https://github.com/aurovrata/guppy/blob/master/src/guppy_backend.js).  If you feel these changes could be of interest to your plugin evolution, please feel free to re-use.

I am writing a WordPress plugin (GPLicensed) which allows for form number fields to be used into calculations to derive values from user inputs.  The custom calculations are captured using guppy mathematical formulas (converted to php) and therefore I need the flexibility to add/remove new symbols which corresponds to these form fields.

**Comment by daniel3735928559** [comment]
Cool--thanks for the work!  I've incorporated it so there's now backend.add_symbol, backend.add_symbol_raw, and backend.add_symbol_func.  These are documented in doc/api.md.

**Comment by aurovrata** [comment]
Nice, I will update my code so that I can easily incorporate updates.
