### ISSUE TITLE
Symbols text with same intial characters not accessible in the editor

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#61]
When 2 or more symbols with the same starting characters are added, for example lqt and lqtu, the 2nd one is inaccessible in the editor as the symbol conversion event is fired too quickly.  Maybe a delay settings can be configured in the instantiation of the editor to allow for longer text to be entered?

**Comment by daniel3735928559** [comment]
Yeah, this is an issue inherent to how the editor works now.  I like the autocompletion a lot for how fast it makes entering most things, but then occasionally there is an issue like this.

There are multiple things a user can do, none of them super simple, but all of them work: 

* Enter `l [SPACE] q t u [TAB]`

* Enter `\ l q t u [ENTER]`

* Enter `l q t Ctrl+z u`

* You can set autoreplace = false in the settings and then enter `l q t u [TAB]` (or the backslash version above). 

The problem with setting a delay is that the normal operation of the editor in a vast majority of cases would be impeded by the rare (though relevant case) like this one.  If you have any ideas for an alternative that is perhaps a bit more intuitive, I'm all ears.

**Comment by aurovrata** [comment]
oh yes, that makes sense!  thanks for the clarification.
