### ISSUE TITLE
Events not firing as expected

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#62]
HI Daniel,

I tried biding the following events, 
`ready change left_end right_end done completion focus`

but none of them fired except `focus` on initial entry.

~~I also tried to get it to fire from the "events" configuration options,~~
```
new Guppy("my-id",{
       "events":{
         "focus": function(focused){
           }
      }
});
```
~~but couldn't get it to work.  The `focus` event which was fired on the guppy element (which I successfully binded to) would not fire within the instantiation configuration settings.~~

PS: Maybe I should try the latest version of your code...(?)

Turns out the `focus` event is fired in the instantiation with the new code.

**Comment by daniel3735928559** [comment]
All of those events seem to be working for me.  What is your code for binding them?  Currently I believe the only mechanism is to pass functions through the "events" object in the constructor.

**Comment by aurovrata** [comment]
I tried,

```
$('#my-id').on('ready change left_end right_end done completion focus', function(){
 ...
});
```
but only `focus` fired when in-focus

**Comment by aurovrata** [comment]
I confirm that they all work in the "events" object.  Except for `completion` which I didn't manage to fire somehow.  Maybe I misunderstood its event.

**Comment by daniel3735928559** [comment]
Ah--yeah, I think that binds to browser events.  Right now the only way to bind Guppy events is through the constructor.  the `completion` event is for when you're in the backslash element and typing a symbol name and press "tab" and there's more than one possibility.  For example, if you enter `\de[TAB]` then you'll get a completion event firing with argument 
`{"candidates":["defi","delta","deriv"]}`.  This would let you do things like display all the possible completions to the user out of band (like tab completion in bash).

**Comment by aurovrata** [comment]
oh, very nice feature this `completion` event!
