### ISSUE TITLE
Pre-fill editor

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#63]
I tried to pre-fill the editor by using the `options` configuration but couldn't get it to work...
```
new Guppy("gfn",{
       "options":{
         "xml_content": "<m><e>1+1</e></m>"
       }
     });
```
am I missing something?

**Comment by daniel3735928559** [comment]
It looks like I broke that feature accidentally.  It should now be fixed.

**Comment by aurovrata** [comment]
thanks, it works now
