### ISSUE TITLE
Can't write exponent/multiplication

### ISSUE THREAD

**Issue by briskweb** [daniel3735928559/guppy#64]
In Firefox, I can't write an exponent on a keyboard with german layout using the ^ key. Typing exp works as expected.

In Chrome, exponent works but I can write the multiplication sign only with the numpad.

**Comment by daniel3735928559** [comment]
Guppy uses Mousetrap.js for keyboard handling, and it looks like Mousetrap has an open issue about this: ccampbell/mousetrap#239.  

I can probably try to write a temporary fix if you can provide me with all the values in the table [here](http://elv1s.ru/files/js/key-code-detector.html) when you press the keys of interest in Chrome and Firefox.  

Meanwhile, you can also use Shift+up arrow to make exponents.

**Comment by briskweb** [comment]
Thank you for your reply.
Apparently, the Firefox problem only exists in Linux (it works in Windows). The table you linked just returns zeros when I press ^ in Linux.

The problem in Chrome with the multiplication sign exists both in Linux and Windows. These are the values in Chrome when I want to write * (using shift+"+"):
keypress	keydown	keyup	input	textInput
keyCode	42	187	16	undefined	undefined
charCode	42	0	0	undefined	undefined
which	42	187	16	undefined	0
data		*

**Comment by briskweb** [comment]
The problem with the multiplication sign together with Chrome and german keyboard layout still exists. Guppy writes a + instead of the multiplication sign.

I figured out that Guppy binds the "shift+=" key, which causes the problem:
https://github.com/daniel3735928559/guppy/blob/d9336ded3394554b783dba4dc01e7869e3651dc4/src/guppy.js#L810

This is related to issue #53 and I would suggest to remove this line. I would also remove "shift+/" in Guppy.kb.k_chars and Guppy.kb.k_text.

**Comment by briskweb** [comment]
This solved it. Thank you for fixing it and all your efforts to Guppy.
