### ISSUE TITLE
Remoce symbol from editor collection

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#67]
Hi Daniel

in my original code change, I had introduced a `remove_symb` allowing me to remove symbols from the editor instance collection, and therefore giving more control as to what the user can enter into the editor.

This is a function I need because I am building a set of symbosl based on the design of an hmtl form and the fields present in that form.  When an admin users changes the form (removes fields) I want to be able to remove the corresponding symbol.  Would you mind introducing a remove function ?

**Comment by daniel3735928559** [comment]
This seems reasonable.  I shall add it.

**Comment by daniel3735928559** [comment]
Almost forgot about this since the issue was closed--apologies.  I've now gone back and added something that should do the job: GuppyBackend objects now have a remove_symbol(name) function.

**Comment by aurovrata** [comment]
oh nice, I hadn't noticed since I was still using my modified trunk.  Am going to upgrade to your latest version now.
