### ISSUE TITLE
IOS guppy probelm

### ISSUE THREAD

**Issue by abhinov2** [daniel3735928559/guppy#68]
While loading on IOS , button layout does come but none of the buttons are clickable.
Same problem occurring on Microsoft Edge.
Pages involved -
1.osk.html
2.guppy_osk.js

**Comment by daniel3735928559** [comment]
Interesting.  I don't have a reliable way of testing on iOS but I'll at least be able to look into Edge compatibility when I next get a shot at this.  I'll see what I can do to poke around in the Apple-flavoured direction also.

**Comment by abhinov2** [comment]
problem solved. i used touchstart in place of click in osk.html key.addEventListener("touchstart", touchStart, false); this solved problem.
but could u urgently look into the problem of not being able to give space between letters.
i tried using phantom  character/ other latex symbols of spacebar but though i am able to create space the problem is the div in which everythng is being displayed is becoming inactive. if i click it again then am able to write further.

**Comment by daniel3735928559** [comment]
I don't have an iDevice to test this on, but I've implemented what I understand from your description and the documentation, and it at least doesn't seem to have broken the Chrome simulation of mobile behaviour.  Try it now and let me know whether it works.  

If it doesn't, I'd be interested to see your actual code.  I'll also look for a chance to test it on a real iPad if need be.
