### ISSUE TITLE
Unable to get editor element when event triggered

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#71]
Hi Daniel,

I am unable to get the guppy editor element that triggered an event, I tried the following
```
gfunctions[id] = new Guppy(id,{
        "events":{
          "change": function(event){
            var $target = $(event.target); //undefined
            $target = $(this) //not an element.
          }
});
```
as you can see I am tracking several guppy editors on the same page and would like to identity which one has triggered the 'change'.  

I modified the backend code to pass the `editor` object to the GuppyBackend object so as to be able to pass it at the event.target object when an event is fired, here are the lines I changed to get it to work in my copy,

1. in the guppy js file, I added an extra attribute to the `GuppyBackend` constructor, 
`this.backend = new GuppyBackend(config, this.editor);`
2. in the guppy-backend js file, I modified the event ('change') trigger,
`this.fire_event("change",{"target":this.editor, "old":this.undo_data[this.undo_now-1],"new":this.undo_data[this.undo_now]});`

would you consider adding this to all event firing in your plugin?

**Comment by daniel3735928559** [comment]
Ah!  This is quite an oversight--thanks for pointing it out.  I've fixed it by making the arguments to every event contain a "target" element (like in your example, but it happens in the `fire_event` function and so applies to all events automatically).  In this case, `event.target` will be the Guppy object that triggered the event (or, if it was just a GuppyBackend object with no associated Guppy object, it will be that GuppyBackend object).

**Comment by aurovrata** [comment]
brilliant, many thanks :)

**Comment by aurovrata** [comment]
I noticed that you are exposing the entire Guppy object under event.target rather than just the `editor` (guppy_div) element.  Is that intended?  Would you rather not expose the object properties through methods to retain control?
