### ISSUE TITLE
Making a donation

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#72]
HI Daniel,

do you have a Guppy home page / paypal account to which one can make a donation?

I am going to be releasing my plugin on the WordPress repo and would like to enumerate the various javascript plugins I used and provide links to users who feel so inclined to contribute to your plugin effort.

**Comment by daniel3735928559** [comment]
I appreciate the exposure, however I do not have such a setup at the moment.  If you give me a day or two to look into it, however, I should be able to arrange it.

**Comment by aurovrata** [comment]
Sure, no worries.  I usually set up a paypal account which allows you to [set up a donate button](https://www.paypal.com/in/cgi-bin/webscr?cmd=_pdn_donate_techview_outside) (which links to a particular paypal invoicing as a donation towards your project).  It makes it easy for donators to print a receipt, and for you to track donations :)

**Comment by daniel3735928559** [comment]
Just in case this is still relevant, the new project URL is https://guppy.js.org, and https://guppy.js.org/site/contribute/#money contains the donation link.  Thanks again for all your help in creating issues and testing the fixes.

**Comment by aurovrata** [comment]
sure, always is :)  I will include it in my plugin page.
