### ISSUE TITLE
Set xml content does not show till editor is focused  

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#73]
I am setting up an editor with come previously saved xml content with the `get_content` function.

However, the content does not show up in the editor.  Once I click and focus the editor the content appears as expected.  This wasn't the case with the previous version (2 weeks ago).  Here is what I am doing,

``` 
new Guppy(divid);
.... validate some symbols.
Guppy.instances[divid].backend.add_symbols(...);// add the validated symbols
Guppy.instances[divid].backend.set_content(xml); //set the content in the newly created guppy function
```
any idea why this is happening?

**Comment by aurovrata** [comment]
is there maybe a way to refresh the editor once I have set the xml so it shows the content properly?

I tried calling the `activate()` function but with no success.

**Comment by daniel3735928559** [comment]
In this case, the answer would be `my_guppy_object.render(true)`, but in fact this is a rather general problem, so I've fixed it by adding such a call to the checkpoint function (which is called whenever the document is changed).

**Comment by aurovrata** [comment]
Magic!  I updated to the latest code, but my functions wouldn't display.  So I added a `Guppy.instances[id].render(true)` and now it shows up.  Thanks!
