### ISSUE TITLE
Decimal numbers interprated with spaces in `text` mode

### ISSUE THREAD

**Issue by aurovrata** [daniel3735928559/guppy#75]
Hi Daniel

came across a strange  error the other day.  a function had a decimal  factor of '0.55' multiplying some variable value x.  However, when extracting the 'text' value of the function, the string formed was,
`0 . 55*x`
space were introduced on either side of the decimal point.  I am assuming that the plugin assumed it to be a dot operator.  

To get round this issue, I rewrote the equation as 55x/100.
Any way to fix this? Possibly using a regex pattern to filter out decimal values from dot operations?

**Comment by daniel3735928559** [comment]
Ah, well caught.  The text stuff gets plumbed through some regexes to try to smooth them out, and these were not handling decimals.  Should be fixed now.

**Comment by aurovrata** [comment]
works fine now, thanks
