### ISSUE TITLE
No proper support for equalities

### ISSUE THREAD

**Issue by blueridanus** [daniel3735928559/guppy#76]
An equality such as `x=2` gives the following output:

LaTeX: 
`x=2`
Text:
`x = 2`
JSON:
`["blank"]`
XML:
`<m><e>x=2</e></m>`

**Comment by daniel3735928559** [comment]
Correct--all expression boundaries (=, !=, <, >, etc) still need support from the syntax tree code.  The syntax tree business is all very fresh and this shouldn't be hard (though it will be a few hours before I can get to it).  However, the interface will have to change slightly: My current plan is that something like `2 < x <= 5` will return an array of comparisons like:

```
[
  ["<", [["val", [2]], ["var",["x"]]],
  ["<=", [["var", ["x"]], ["val",[5]]]
]
```
meaning that something like `x+2` should probably also return an array of expressions (containing jut the one expression: 
```
[
  ["+", [["var", ["x"]], ["val",[2]]]
]
```

which is a little odd but not terrible.

**Comment by daniel3735928559** [comment]
OK, so after more thought, the interface is now as follows: `get_content("ast")` returns a faithful representation of the syntax tree: `2 < x <= 3` becomes (formatted for readability): 
```
["<=",[
  ["<",[
    ["val",[2]],
    ["var",["x"]]]],
  ["val",[3]]]]
```
which, while not probably not super meaningful in most cases, is an accurate representation of what's happening.  Meanwhile, `get_content("eqns")` (name subject to change--it's more "comparisons" or something) does a tiny amount of post-processing on that to derive the actual list of comparisons: 

```
[
  ["<",[["val",[2]],["var",["x"]]]],
  ["<=",[["var",["x"]],["val",[3]]]]
]
```

**Comment by daniel3735928559** [comment]
This is now described on the website, in the documentation, and in some tests, so I'm going to close the issue.
