### ISSUE TITLE
Text is handled as multiplication

### ISSUE THREAD

**Issue by blueridanus** [daniel3735928559/guppy#78]
User input:
`textfoo`
LaTeX output:
`\text{foo}`
Text output:
```text( f * o * o )  ```
JSON output:
```["text",[["*",[["*",[["var",["f"]],["var",["o"]]]],["var",["o"]]]]],{}]```
XML output:
```xml
<m><e></e><f type="text" group="editor"><b p="latex">\text{<r ref="1"/>}</b><b p="text">text(<r ref="1"/>)</b><c mode="text"><e>foo</e></c></f><e></e></m>
```

Additionally, treating an input such as `bar` as the multiplication of three variables `b*a*r` might be a bit confusing and unergonomic as default behaviour. Perhaps, instead, each new keypress should extend the variable's name until the user presses space.

**Comment by daniel3735928559** [comment]
Good call.  Should be fixed now.  I'll leave this open as a reminder to add a test that covers this.

**Comment by daniel3735928559** [comment]
There's now a test for this.  Closing.  Thanks again.
