### ISSUE TITLE
Problem in "start to type" functions

### ISSUE THREAD

**Issue by librilex** [daniel3735928559/guppy#79]
There is a problem in the start to type function, when the word to type includes another word which triggers the conversion. On the demo page this can be seen when you want to enter the greek letters `epsilon`, `upsilon`, `zeta` and `theta` which are then converted to `eψlon`, `uψlon`, `zηa` and `thηa` instead of `ε` and `υ`, `ζ` and `θ`, respectively.
I had the same problem with my custom functions `vartheta` and `arcsin`, whose output is converted falsely to _var_ thηa and _arc_ sin() instead of `ϑ` and `arcsin()`, respectively.

It would be great if there was a check or something if the word was entered by itself (in its own node or something similar) or if the typing has not been finished yet.

**Comment by daniel3735928559** [comment]
Yeah.  I like the autocompletion when it works, but am not sure what to do in these other cases.  A few things that exist currently: 

* You can enter full symbol names without any autocompletion (but with tab completion) by typing e.g. `\vartheta` and then pressing "enter".

* You can undo the step where it autocompletes with Ctrl-z and continue typing (doesn't solve "theta", but does solve "epsilon").  

* When you initialise an editor, you can set "autoreplace":false, which means that nothing will be automatically replaced and you'll need to hit TAB to create symbols.

Your idea about the whole node or delay are interesting and wouldn't be too hard to implement as other configurable options.  Let me look into this and think about other possible options also.

**Comment by daniel3735928559** [comment]
I've implemented "autoreplace":"whole" as an option now.  You can try it out on the demo page by 

* Focus the editor
* Click the gear "settings" icon
* Change the "autoreplace" parameter to "whole"
* Try typing inputs

So `x s i n` will not autoreplace, `x + s i n` will, and epsilon, zeta, theta, etc work as expected under that configuration.  This also accepts space as a separator, so if you type `x SPACE s i n` this will autoreplace with `x sin()`.

I'll look into a delay option also.

**Comment by daniel3735928559** [comment]
OK, I've implemented "autoreplace":"delay" as well, which delays autoreplacement by 200ms.  It's a little weird.  

I've also made it so that the longest matching symbol name is selected, rather than the shortest, so arcsin, vartheta, and simliar should all now work correctly even in the default mode.  

Feel free to reopen if you're finding some combination of these options/methods insufficient.

**Comment by librilex** [comment]
Thank you for adding the new autocorrect types. I have tested "whole" so far and it works as expected. I will also try the "delay" mode, but will probably stick to the "whole" function.

Thanks again!
