### ISSUE TITLE
Error when inserting strings with ^

### ISSUE THREAD

**Issue by jiggzson** [daniel3735928559/guppy#83]
I've noticed that you changed  the way that strings are inserted into guppy
```javascript
//from:
guppy.insert_string();
//to
guppy.engine.insert_string();
```
If I got that part right then I get the following error when trying to insert the string "x^6"
```console
katex-modified.min.js:2 Uncaught Error: KaTeX parse error: Expected group after '^' at position 79: …py_loc_m_e1_1}{^̲}\xmlClass{gupp…
    at new e (katex-modified.min.js:2)
    at e.t (katex-modified.min.js:2)
    at e (katex-modified.min.js:2)
    at e.t (katex-modified.min.js:2)
    at e (katex-modified.min.js:2)
    at e (katex-modified.min.js:2)
    at e (katex-modified.min.js:2)
    at e (katex-modified.min.js:2)
    at e.t (katex-modified.min.js:2)
    at e (katex-modified.min.js:2)
```
Am I doing something wrong?

By the way, one issue I ran into is that I had to update my version of katex to whichever version guppy uses (in my case the latest) or else you run into conflicts with the way LaTeX on the rest of the page is rendered.

**Comment by daniel3735928559** [comment]
I'm not sure exactly what you're trying to do, but if you want to programatically insert something like that, you can do, e.g., 

```javascript
guppy.engine.insert_string("x")
guppy.engine.insert_symbol("exp")
guppy.engine.insert_string("2")
```

Or, if you want to insert a document fragment, you can do so with the (new!) `Engine.insert_doc` like `guppy.engine.insert_doc(some_doc)`, where `some_doc` is a `Guppy.Doc` instance representing the fragment you want to insert.  For example, to do what you're doing, you could do `guppy.engine.insert_doc(new Guppy.Doc("x^6","text"))`, which would parse the text "x^6" into a document and then insert that document at the cursor position.

**Comment by jiggzson** [comment]
In my case the string is parsed and symbolically manipulated so let's say
```
diff(x^7+1,x); //x^6
```
The user uses guppy for inserting this expression. The output is displayed in the form of LaTeX using KaTeX.  The output needs to at some point be loaded back to the guppy input. This is where I used to use
```javascript
guppy.insert_string();
```
and this worked perfectly. I'll give the provided solution a go and hopefully this solves it.

**Comment by jiggzson** [comment]
This is my code
```javascript
//Clears the input
function clear() {
    if(USE_GUPPY) {
        guppy.engine.set_content('<m><e/></m>');
        guppy.render(true);
    }
    else {
        //$('#text-input').val('');
        editor.setValue('');
    }    
}

function setInputValue(value) {
    clear();
    if(USE_GUPPY) {
        guppy.engine.insert_doc(new Guppy.Doc(value,"text"))
        //guppy.engine.insert_string(value);
        guppy.activate();
    }
    else {
        //textInput.val(value);
        editor.setValue(value);
    }    
}
```
Here USE_GUPPY = true since Guppy is the editor being used. The value in this case is the 'x^6' we discussed before. When I try using the solution you provided I get this

```console
Uncaught TypeError: guppy.engine.insert_doc is not a function
    at setInputValue (demo.js:236)
    at HTMLAnchorElement.<anonymous> (demo.js:383)
    at HTMLDivElement.dispatch (jquery.js:3)
    at HTMLDivElement.r.handle (jquery.js:3)
```
In this case guppy is my guppy instance and it claims not to have an insert_doc function. Below is a partial of the guppy instance from the chrome console.

```javascript
Guppy {id: "demo-input", buttons_div: div.guppy_buttons, editor_active: false, editor: div#demo-input.demo-input.guppy_inactive, blacklist: Array(0), …}
```

**Comment by daniel3735928559** [comment]
Ah, I see; that makes sense given your application.  `insert_doc` is more for if you want to insert something into an existing document.  (Also, it's new, so you might have to git pull to get it.)  However, if you want to overwrite the whole document with e.g. the result of a calculation, `guppy.import_text("x^6")` should work.  This should accept anything that would be outputted by `guppy.text()`

**Comment by daniel3735928559** [comment]
Also, I'm surprised `insert_string` ever worked for this purpose.  At the very least I would expect the resulting document not to have been editable without errors.  Do you recall if this was the case?

**Comment by jiggzson** [comment]
`guppy.import_text("x^6")` did the trick. 
>Also, I'm surprised insert_string ever worked for this purpose.

It did ironically. The first iteration of guppy worked flawlessly with my library down the naming of the functions. It literally took me a couple of hours of reading and coding I was done. Keep in mind that my library does symbolic math so this project is a natural fit. I tried using Mathquill in the past but never got it to work because of the way it handles text. The only thing that stopped me from using Guppy as my primary editor was the fact that I couldn't  get the keyboard to work on mobile devices. 

This time around I'll have a bit of work to do since the functions have been renamed, for instance **integrate** has been renamed to **definite_integral**, **diff** doesn't work anymore since it's probably been renamed as well. I guess this is where the symbols.json comes in so no biggie at all. Maybe I can even drop in the old one. 

Thanks for all your hard work.
