### ISSUE TITLE
Issues with adding symbol for 2D column array (LaTeX' cases environment)

### ISSUE THREAD

**Issue by librilex** [daniel3735928559/guppy#84]
I might have found two issues when adding a symbol with two variables which is supposed to add a two-dimensional column array.

I wanted to add the LaTeX' cases environment to Guppy in such manner:
```latex
x=\begin{cases}
  x_1 &\text{if } k=0 \\
  x_2 &\text{if } k=-1 \\
  x_3 &\text{if } k=1 \\
\end{cases}
```
I added the following code to my JSON:
```json
    "cases":
    {"output":{
        "latex":"\\begin{cases} {$1{\\\\}} &\\text{if } {$2{\\\\}} \\end{cases}",
        "asciimath":"cases({$1{;}}, if {$2{;}})"
         }
     },
```

Trying it out in Guppy, it seems to work fine at first until a new line/case is added:
![grafik](https://user-images.githubusercontent.com/26027208/34611581-585efc40-f226-11e7-8310-42e47bef5c24.png)

First of all, I could not add a new row by using `Ctrl` + `Up`/`Down` or `;` as expected - I had to add it by using `Ctrl` + `Left`/`Right` or pressing `,`. Is there a reason for this or is this a bug?
It would be great if `{\\\\}` is used that it is automatically recognized that rows instead of new columns are added and `Up` and `Down`.

When adding a new row, only the first variable item`$1` is added and the second item `$2` remains in either the first row (when adding a new row in the `$2` field) or moves into the last row (when adding a new row in the `$1` field). It seems that I have used the wrong syntax to allow `$i` variables to simultaneously be added in a new row. How could I achieve that?

**Comment by daniel3735928559** [comment]
Notionally, the way to do this is:

```
    "cases":
    {"output":{
        "latex":"\\begin{cases} {$1{ & \text{ if } }{\\\\}} \\end{cases}",
	"asciimath":"cases({$1{ if }{;}})"},
     "attrs":{
	 "group":"array",
	 "type":"cases"}
    },
```

However, there is a bug with the way the arguments are parsed that makes this not quite work properly.  I know what the problem is and should have time to fix it later today.

**Comment by daniel3735928559** [comment]
OK.  It was a little more involved than I anticipated, but it works now.

**Comment by librilex** [comment]
Thank you for fixing it! However, I am not sure how the correct syntax is. I tried

```JSON
    "cases":
    {"output":{
        "latex":"\\begin{cases} {$1{ & \text{ if } $2}{\\\\}} \\end{cases}",
	"asciimath":"cases({$1{ if } $2{;}})"},
     "attrs":{
	 "group":"array",
	 "type":"cases"}
    },
```
and some other ways, but I either received an error or was not possible to add the second argument. Could you please tell me how to use it?

**Comment by daniel3735928559** [comment]
I did it with 

```javascript
    "cases":
    {"output":{
        "latex":"\\begin{cases} {$1{ & \\text{ if }}{\\\\}} \\end{cases}",
	"asciimath":"cases({$1{ if } $2{;}})"},
     "attrs":{
	 "group":"array",
	 "type":"cases"}
    },
```

The idea is it's basically a matrix with columns separated by "if" and rows separated by newlines.  This has the disadvantage that it's possible to add more than two columns, which is improper.  However right now the array syntax doesn't support anything more complex than specifying column separators and row separators.  (For instance, the thing you're trying to do with an array where each entry has two arguments isn't currently supported.  I will think about a more general specification that might support more use-cases like this in the future.)

**Comment by librilex** [comment]
Ah, I see. Thanks for clarifying!
