### ISSUE TITLE
Enter absolute value with "|"

### ISSUE THREAD

**Issue by fjch1997** [daniel3735928559/guppy#85]
**Current behavior**
Keystroke is ignored (nothing happens) when the user type in "|".

**Expected behavior**
- Insert absolute value signs. Equivalent to `\abs` `enter`
- Make it possible to inset `ln|x|`  instead of `ln(|x|)`

Just some suggestions for future work. This is an already very nice library for its support on both input and output of multiple formats. Thanks so much Daniel!

**Comment by daniel3735928559** [comment]
Ah--good catch.  The `|` thing was supposed to work but was using and old type name.  

The second thing can sort of be accomplished now by replacing the `latex_func` template in symbols.json with the following: 

```
	"latex_func":{"output":{"latex":"\\{$name} {$1}",
			  "asciimath":" {$name} {$1}"},
		"attrs":{
		    "type":"{$name}",
		    "group":"functions"},
		"args":[
		    {"delete":"1","bracket":"yes"}
		]},
```

The difference is that this will also cause something like `ln(x)` to render as `ln x` by default (though this is notation that is used sometimes too, and also `ln(x+1)` will still render with brackets--basically, it will only add brackets when it needs to, and will know not to add them to `ln|x|`).  If that is unsuitable, I can try to think about something more flexible.  

(I'm still trying to avoid having symbols files contain actual code so they can be exchanged/reused without needing a security audit each time, for example.  We'll see how far that goes.)

**Comment by fjch1997** [comment]
The latest commit https://github.com/daniel3735928559/guppy/commit/e5ecc61f41a8682afaf37609354c685bf5a7ebe9 works, thanks!

For the second part. I think `ln x ` is perfectly valid, so long as it adds the parenthesis when there are more than one elements. I do this when writing by hand too.
