### ISSUE TITLE
Dynamically resize the input box

### ISSUE THREAD

**Issue by vimeitor** [daniel3735928559/guppy#87]
Firstly, thank you for the project. It's been very helpful so far :-).

I think it would be a wise idea to resize the input box (the div, basically) so that long formulas don't end up outside of the div.

**Comment by daniel3735928559** [comment]
Hello, and you're welcome!

This can be done by setting the div that you initialise the editor with to have `display:inline-block;`.  I set the width on the example page to be fixed for, I suppose, aesthetic reasons.  

For the best of both worlds, you can set `min-width:[something reasonable]` and `display:inline-block`.

**Comment by vimeitor** [comment]
Oh, thank you! I always use your website to generate the equations and then paste them on the document, so I will most likely use some extension that allows me to change the stylesheet permanently.
