### ISSUE TITLE
Add support for log base and powers to functions

### ISSUE THREAD

**Issue by Debaj1** [daniel3735928559/guppy#89]
**Current behavior**
Cannot add base to log function_

**A support for them needs to be added.**

**Comment by JMSS-Unknown** [comment]
You can create a new symbol to support logs with bases. This is what I use
`"logbase":{
    "output":{
      "latex":"\\log_{{$1}}\\left({$2}\\right)"
    },
    "attrs":{
      "type":"logbase"
    },
    "args":[
      {
        "down":"1",
        "up":"2",
        "small":"yes",
        "name":"base",
        "bracket":"no"
      },
      {
        "down":"1",
        "up":"2",
        "small":"no",
        "name":"value",
        "bracket":"no"
      }
    ]
  }`
