### ISSUE TITLE
Update KaTeX to latest version

### ISSUE THREAD

**Issue by JMSS-Unknown** [daniel3735928559/guppy#92]
In the current version of KaTeX being used, sometimes dividing lines for fractions and overhead lines for square roots disappear. This seems to be fixed in the latest release of KaTeX, v0.10.0-alpha.

**Comment by saivan** [comment]
We were discussing this, and we'd like to move to a system that just patches KaTeX, so that we don't need to keep applying the same changes to the main KaTeX source. This will result in an update to the latest version hopefully.

**Comment by daniel3735928559** [comment]
This is now done--let me know if the KaTeX-related issues you observed are fixed.

**Comment by saivan** [comment]
So, can this always track the latest version now? Or does it still need to be manually updated every time?

**Comment by daniel3735928559** [comment]
It's a little in between for now.  It does have to be manually updated, but as long as a few internal interfaces stay stable, this should be as easy as adding one new file and one line to an existing file.  

From the discussion on KaTeX/KaTeX#1791 (referencing KaTeX/KaTeX#1437), it sounds like they intend to add a `\class` function properly, which is all that we currently need in addition to stock KaTeX.

To patch KaTeX from outside would either still require modifications to KaTeX to expose internal functions, or else possibly some fairly ambitious object spelunking to get at the internal APIs from the outside.  My preference is to just keep KaTeX/KaTeX#1791 up to date until no longer needed, as this shouldn't be too much work.

As a final note, MathJax already support `\class`.  Playing with their live demo, it doesn't look fast enough for this application, but I know they're interested in speeding things up, so could also be worth keeping an eye on.

**Comment by saivan** [comment]
yes, I am aware that mathjax has class too. Mathjax 3 should be out soonish though :)
