### ISSUE TITLE
Pressing "tab" to move to next guppy box

### ISSUE THREAD

**Issue by brandonpek** [daniel3735928559/guppy#95]
I was wondering if there was a way such that "tab" key would move focus out of the Guppy instance into the global tab order?

**Comment by daniel3735928559** [comment]
This was not really possible before.  However, I've now exposed the Mousetrap object as `Guppy.Mousetrap` so you can edit global Guppy bindings if you need to.  In your case, 

```
Guppy.Mousetrap.unbind("tab");
```

should do the trick

**Comment by daniel3735928559** [comment]
I've tested this and it seems to work.  If it doesn't do what you need, feel free to reopen.
