### ISSUE TITLE
Can't test with "npm test"

### ISSUE THREAD

**Issue by wssssh** [daniel3735928559/guppy#98]
I had run 
```
git clone https://github.com/danie13735928559/guppy
cd guppy
npm install --only=dev
npm run-script build-debug
```
When I run `npm test`,it says  
![image](https://user-images.githubusercontent.com/25715031/44708944-fe400100-aada-11e8-94c2-77871675c194.png)
What should I do to fix it?

**Comment by wssssh** [comment]
when i run `npm install --only=dev`
![image](https://user-images.githubusercontent.com/25715031/44709060-49f2aa80-aadb-11e8-8233-6eb7660e4e83.png)
Is it right?

**Comment by saivan** [comment]
I think you have to download the chrome web driver:
http://chromedriver.chromium.org/

If you have brew (on a mac), you can just do:

```
brew cask install chromedriver
```

Then it should work

**Comment by daniel3735928559** [comment]
Since the full error message on the line you posted was 
```
      throw Error(
          'The ChromeDriver could not be found on the current PATH. Please ' +
          'download the latest version of the ChromeDriver from ' +
          'http://chromedriver.storage.googleapis.com/index.html and ensure ' +
          'it can be found on your PATH.');
```

I think saivan's answer is the right one.  

As to the question about vulnerabilities, afaict the remaining ones need to be fixed upstream, but are all in the dev dependencies so shouldn't affect deployment.

**Comment by wssssh** [comment]
Thanks for reply! Saivan's answer is right.I have solved this problem.Thank you.

**Comment by daniel3735928559** [comment]
chromedriver is now included as an explicit dependency and karma finds it automatically, so this should no longer be an issue.
